version: "3"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      # 将宿主机的后台源码映射入容器内，以便感知文件变动
      - ./backend:/usr/src/app
      # 映射独立的 target 构建缓存，防止在 Windows 系统和 Linux 容器之间出现 target 锁死或交叉污染
      - backend-target:/usr/src/app/target
      # 映射 Cargo 安装包目录，加速每次重建依赖的下载
      - cargo-registry:/usr/local/cargo/registry
    environment:
      - CARGO_TARGET_DIR=/usr/src/app/target

volumes:
  backend-target:
  cargo-registry:
