FROM rust:1.94-slim-bullseye

WORKDIR /usr/src/app

# 安装必要的依赖库
RUN apt-get update && apt-get install -y pkg-config libssl-dev libsqlite3-dev git

# 安装 cargo-watch 工具用于热重载
RUN cargo install cargo-watch

# 在开发模式下，利用 cargo watch 监听文件变化并自动执行 cargo run
CMD ["cargo", "watch", "-c", "-w", "src", "-x", "run"]
