ALTER TABLE user_levels ALTER COLUMN id TYPE BIGINT;
ALTER TABLE user_levels ALTER COLUMN daily_invite_limit TYPE BIGINT;
ALTER TABLE user_levels ALTER COLUMN marketing_enabled TYPE BIGINT;
ALTER TABLE user_levels ALTER COLUMN is_default TYPE BIGINT;
ALTER TABLE user_levels ALTER COLUMN max_token_count TYPE BIGINT;

ALTER TABLE users ALTER COLUMN is_active TYPE BIGINT;
ALTER TABLE users ALTER COLUMN admin_group_id TYPE BIGINT;

ALTER TABLE api_tokens ALTER COLUMN id TYPE BIGINT;
ALTER TABLE api_tokens ALTER COLUMN is_active TYPE BIGINT;

ALTER TABLE channels ALTER COLUMN id TYPE BIGINT;
ALTER TABLE channels ALTER COLUMN preset_id TYPE BIGINT;
ALTER TABLE channels ALTER COLUMN pool_id TYPE BIGINT;
ALTER TABLE channels ALTER COLUMN gptimage_pool_id TYPE BIGINT;

ALTER TABLE logs ALTER COLUMN id TYPE BIGINT;
ALTER TABLE logs ALTER COLUMN channel_id TYPE BIGINT;
ALTER TABLE logs ALTER COLUMN token_id TYPE BIGINT;

ALTER TABLE task_logs ALTER COLUMN id TYPE BIGINT;
ALTER TABLE task_logs ALTER COLUMN channel_id TYPE BIGINT;

ALTER TABLE channel_configs ALTER COLUMN id TYPE BIGINT;

ALTER TABLE admin_groups ALTER COLUMN id TYPE BIGINT;

ALTER TABLE plugins ALTER COLUMN id TYPE BIGINT;
ALTER TABLE plugins ALTER COLUMN is_enabled TYPE BIGINT;
ALTER TABLE plugins ALTER COLUMN size TYPE BIGINT;
ALTER TABLE plugins ALTER COLUMN sort_order TYPE BIGINT;

ALTER TABLE site_icons ALTER COLUMN id TYPE BIGINT;
ALTER TABLE site_icons ALTER COLUMN is_active TYPE BIGINT;
ALTER TABLE site_icons ALTER COLUMN total_synced TYPE BIGINT;
ALTER TABLE site_icons ALTER COLUMN total_new TYPE BIGINT;
ALTER TABLE site_icons ALTER COLUMN total_updated TYPE BIGINT;

ALTER TABLE redemption_codes ALTER COLUMN id TYPE BIGINT;

ALTER TABLE models ALTER COLUMN id TYPE BIGINT;

ALTER TABLE volcengine_pools ALTER COLUMN id TYPE BIGINT;
ALTER TABLE volcengine_pools ALTER COLUMN pool_id TYPE BIGINT;
ALTER TABLE volcengine_pools ALTER COLUMN account_id TYPE BIGINT;
ALTER TABLE volcengine_pools ALTER COLUMN channel_id TYPE BIGINT;

ALTER TABLE gptimage_pools ALTER COLUMN id TYPE BIGINT;
ALTER TABLE gptimage_pools ALTER COLUMN pool_id TYPE BIGINT;
ALTER TABLE gptimage_pools ALTER COLUMN account_id TYPE BIGINT;
ALTER TABLE gptimage_pools ALTER COLUMN channel_id TYPE BIGINT;
